### ISSUE TITLE
User Story 1: Projectlist

### ISSUE THREAD

**Issue by marcterre** [marcterre/capstone-project#1]
## Value Proposition

As a User 
I want to choose between my projects 
so that i can have a overview of the details of my project.  

## Description
![User Stroy I(2)](https://user-images.githubusercontent.com/118189611/213469520-77047a74-cc12-478f-b0bc-77f3c2ec12d6.png)

## Acceptance Criteria

- [ ] title is positioned fixed on top of the screen
- [ ] icon is shown before every list item
- [ ] a list of all projects is displayed
- [ ] each project title is displayed for each list item

## Tasks

- [x] create a title and fix it on top of the landingpage
- [x] create a json file with static data for your list with this format:
        [{ "title": "Project 1"}, 
       { "title": "Project 2"}, 
       { "title": "Project 3"}];
- [x] create a project component to render each project data
- [x] import your json file and map over the data: each item should now be listed
- [x] import a icon and add it before every list item

## Complexity

S

**Comment by marcterre** [comment]
thanks for your review, i updated everything 🙂

**Comment by mbosselmann** [comment]
Hi Marc,
great job! :octocat: We only have two remarks, but nothing that would hinder us to approve your user story now.

Our last remarks:
- it would be nice to see example values in your example data (we think that "..." are not correct project names)
- And: "import your json file and map **over** the data: each item should now be listed"

Happy hacking! 🚀

**Comment by marcterre** [comment]
Fixed it! Thanks again for your effort, appreciate it 😊
