### ISSUE TITLE
User Story 6: Views detail page

### ISSUE THREAD

**Issue by marcterre** [marcterre/capstone-project#11]
## Value Proposition

As a User 
I want to have a look at my view i created
so that i can read the details for the view.

## Description

![User Stroy 6(1)](https://user-images.githubusercontent.com/118189611/214047728-dcbfab19-a1d0-4224-a8d0-9e0a74cfa874.png)

## Acceptance Criteria

- [ ] there is a link on the project details page with the views name which leads to the view details page
- [ ] on the views details page there is a title with the name of the view
- [ ] there is a section with a subtitle for the description
- [ ] there is a section with a subtitle for the sketch and for now with a example sketch
- [ ] there is a back-button which leads back to the project details page

## Tasks

- [ ] create a new [slug]page for view-details in pages with a index.js
- [ ] on this page create a title with the view name
- [ ] create a section for the description
- [ ] create a section for the sketch with an example picture (will be changed later)
- [ ] create a "back"-button which leads back to the project details page
- [ ] handle the dynamic routing with useRouter

## Complexity

L

**Comment by minatimar** [comment]
"there is a section with a subtitle for the description and the description" there is one redundant "description" in the acceptance criteria.
the rest lgtm ...

**Comment by JohannesMisch** [comment]
LGTM 👍
