### ISSUE TITLE
User Story 7: Delete button

### ISSUE THREAD

**Issue by marcterre** [marcterre/capstone-project#14]
## Value Proposition

As a User
I want to be able to delete my projects
so that i can always have control over them.

## Description

![Image](https://user-images.githubusercontent.com/118189611/214969002-18b5edd6-0419-43fa-a120-c2c21938c312.png)

## Acceptance Criteria

- [ ] on the project details and the view details page there is a settings button on the top right
- [ ] the button is displayed by a icon
- [ ] clicking the button lets pop up a delete button with a bin icon
- [ ] clicking the delete button will open up a pop up window
- [ ] the background almost disapears behind the pop up window
- [ ] there are two buttons "yes" or "no" in the pop up window
- [ ] clicking "yes" will delete your project/view
- [ ] clicking "no" cancels the delete and leads back to the project-/view- details page

## Tasks

- [ ] create a settings component with the settings button
- [ ] create a component for the delete button
- [ ] in this component create the button with a bin icon 
- [ ] for the bin button set a onClick function which toggles a state. if "true" the pop up window will be displayed
- [ ] create a modal component for the pop up window
- [ ] return a div with a text element for the warning message
- [ ] create two buttons one for "no" one for "yes"
- [ ] for the "yes"-button handle a onClick function for the delete
- [ ] for the "no"-button handle a onClick which sets the state for the pop up windows to "false" so the pop up window is now hidden
- [ ] import the pop up window component into the delete-button component
- [ ] import the delete-button component into the project- and view- details page

## Complexity

XL

**Comment by minatimar** [comment]
does the icon (bin) need a toogle function? you can just click "no" in the pop up to go back to the page..

**Comment by marcterre** [comment]
Hey Mina,  yes the bin button gets a toggle function, which will pop up the window. I have written it in more detail.
Also i did rewrite the tasks for  the "no"-button. Should be more clear now?
