### ISSUE TITLE
User Story 8: edit button

### ISSUE THREAD

**Issue by marcterre** [marcterre/capstone-project#15]
## Value Proposition

As a User 
I want to be able to edit my projects and views
so that i have control over my data.  

## Description

![Image](https://user-images.githubusercontent.com/118189611/214970044-2076c752-3c7c-474e-961c-79610a7d754f.png)

## Acceptance Criteria

- [ ] clicking the settings button will now show a edit button besides the delete button
- [ ] the delete button deletes your project/view ([US 7](https://github.com/marcterre/capstone-project/issues/14))
- [ ] clicking the edit button opens a modal where changeable inputs are shown
- [ ] a "save"-button on the bottom of the modal saves the changes and leads back to the project-/view- details page
- [ ] a "cancel"-button on bottom also leads back but without submitting

## Tasks

- [ ] add a "edit"- button in you settings button component
- [ ] import a modal component and let it be displayed if the edit-button set a State "true"
- [ ] in the modal component create inputs where the changeable inputs with the old values are shown
- [ ] create a "save"-button inside the modal and handle the submit
- [ ] after submitting the modal should close and you should be back to the project-/view- details page
- [ ] create a "cancel"-button inside the model -> onClick: let it lead back to the project-/view- details page without changes

## Complexity

L
