### ISSUE TITLE
User Story 9: Image import

### ISSUE THREAD

**Issue by marcterre** [marcterre/capstone-project#16]
## Value Proposition

As a User
I want to to be able to upload a sketch to my project
so that i can always have a look at my planned design

## Description

![User Stroy 9](https://user-images.githubusercontent.com/118189611/214820757-68358c76-2474-4fbd-b665-fc63f91cf722.png)
![User Stroy 9(2)](https://user-images.githubusercontent.com/118189611/215896815-36f3bfce-7bd1-49a8-90d0-0f92fae6adb1.png)

## Acceptance Criteria

- [ ] the text input field in the form for creating a new project or adding a new view is now a input for image upload
- [ ] the uploaded images are displayed as preview on the details pages
- [ ] if you click on the image it opens a modal with your image in full size
- [ ] on this modal there is also a header with "Your sketch", a close-button and a edit-button
- [ ] clicking the edit button will pop up an file input where you can change your image
- [ ] clicking the delete button will delete your image

## Tasks

- [ ] create a api folder in the pages folder with a upload.js file
- [ ] install and import cloudinary and formidable into this file
- [ ] outside of the pages folder create a env.local and write the keys from cloudinary in the env.local
- [ ] in the upload.js: write a handler function for uploading the files to cloudinary and reveiving back a url
- [ ] change the inputs in the form to type="file"
- [ ] change the submit functions and receive the image url from cloudinary
- [ ] create a ModalSketch Component, add your image in full size
- [ ] inside of the Modal: 
- [ ] create a close button and handle the Close
- [ ] create a edit button and handle the edit
- [ ] create a delete button and handle the onClick so that it deletes the image

## Complexity

XL

**Comment by IrisHerholz** [comment]
Cool feature! How do u  change the url input to a working upload but?

**Comment by RobinWitt** [comment]
Nice wireframes and overall User Story! As Iris said, you could describe more precisely in your Tasks how the image upload is supposed to work and/or what technologies you want to use for that (*hust* Cloudinary *hust*)

**Comment by marcterre** [comment]
Thank you, i added more detailed tasks

**Comment by AGeck113** [comment]
Look's good for me now, have fun coding!
