### ISSUE TITLE
User Story 10: Materiallist

### ISSUE THREAD

**Issue by marcterre** [marcterre/capstone-project#19]
## Value Proposition

As a User
i want to add dimensions to my project-views 
so that i have an overview of the material dimensions

## Description
The wireframe shows the project details page but you can also add dimensions on the view details page. Both detail pages will look the same like below.

![Image](https://user-images.githubusercontent.com/118189611/216359699-195d71cc-6491-405c-9b6a-fe85d412f5e0.png)
![Image](https://user-images.githubusercontent.com/118189611/216359745-85529fb8-c18a-42fe-84be-a0c29dc9fc10.png)

## Acceptance Criteria

- [ ] There is a new section with the subtitle for the "Materiallist" on the project- and view- details page
- [ ] There is a box "click to add new dimensions", when clicked, a card will unfold where you can add new dimensions
- [ ] You can assign a name, material, width, height, depth and the number of pieces you need
- [ ] you can assign a unit of measurement like "mm, cm, m, ft.."
- [ ] If you safe your dimension it will be listed below the box "click to add new dimensions"
- [ ] The materiallist will always be shown on your project- or view- details page
- [ ] Its possible to delete the list items by swiping to the left

## Tasks

- [ ] create a new component for the Materiallist
- [ ] inside of this component:
- [ ] create a ```h2``` for "Materiallist"
- [ ] create a button which toggles a state ex: ```onClick={() => setShowAddDimensions(!showAddDimensions)}```
- [ ] if the state is true a card with a form will unfold
- [ ] create this form with label and input for name, material, width, height, depth and number of peaces
- [ ] create select tag with the options "mm, cm, m, ft...", name it "unit of measurement"
- [ ] create a submit button and handle the submit
- [ ] if the dimensions will be submitted the data should be listet below of the box "click to add new dimensions"
- [ ] install the swipe-library and wrap it around your list items

## Complexity

L

**Comment by JohannesMisch** [comment]
Hey Marc, your user story is really good, I like it.
