### ISSUE TITLE
User Story 2: Project details page

### ISSUE THREAD

**Issue by marcterre** [marcterre/capstone-project#2]
## Value Proposition

As a User
I want to have a details page of my projects
so that i can simply achive the information about my project.

## Description

![Image](https://user-images.githubusercontent.com/118189611/213862763-7ef36b91-95e0-492a-9e90-3bf380175325.png)

## Acceptance Criteria

- [ ] if we click on a project card with the project name the page for the project details is available
- [ ] the project title is fixed on top of the screen
- [ ] there is a section for the description with a example text (will be changed later)
- [ ] there is a section for the sketch which will be displayed later
- [ ] a button fixed on the bottom of the screen leads back to the landingpage

## Tasks

- [x] create a new folder in "pages" for project details with a index.js inside
- [ ] in this index.js:
    - [x] create a static project title and fix it on top of the screen
    - [x] create a section with a subtitle for the description and for now with a example text
    - [x] create a section with a subtitle for the sketch (for now add a example image)
    - [x] create a button with a onClick function and fix the button to the bottom of the screen
    - [x] import the useRouter hook
    - [x] write the onClick function so that it leads back to the landingpage
    therefore use: `router.push("./")`
- [ ] wrap a link tag around your list items on the landingpage which leads to the project details page

## Complexity

S

**Comment by ThomasF85** [comment]
Hi Marc,

your user story should be written so that another developer can take the story and implement it. I have some open questions that should be answered through the description or acceptance criteria of your story:
- Is there a way for the user to access the details page (through a link on the landingpage for example)?
- Is the description section an empty section or does it actually contain the description of the project?

Also we do not want to display empty elements or sections which are essentially useless / confusing to the user. So please remove the section for the sketch.

**Comment by marcterre** [comment]
you right, now it should be clear

**Comment by JohannesMisch** [comment]
Changes were made while we discussed the user Story in Zoom
