### ISSUE TITLE
US 11:  Tasklist

### ISSUE THREAD

**Issue by marcterre** [marcterre/capstone-project#20]
## Value Proposition

As a User
i want to have a list of task for my project
so that i know what i have to do next

## Description

![User Stroy 11(1)](https://user-images.githubusercontent.com/118189611/215712914-c3be3f8a-847c-43b3-9279-384c510e5c54.png)

## Acceptance Criteria

- [ ] on the project details page there is a new tab beside the materiallist
- [ ] you can now switch between the materiallist and the tasklist
- [ ] if you click on the tasklist you have a  button for "add new task" and a ordered list of your task
- [ ] when there is no task yet the section below the box is empty
- [ ] to add a new task you can click a button "add new task" which will unfold a form
- [ ] in this form you can assign a name and a order
- [ ] when submitted the new task will be listed below the "add new task" button

## Tasks

- [ ] create a new component for the tasklist
- [ ] inside of this component:
- [ ] create a button "add new task" and let the button toggle a state, if true the form to add a new task will unfold
- [ ] create a form with two labels and inputs for task and number of order
- [ ] create a submit button and handle the submit
- [ ] import the component to the project details page
- [ ] change the subtitle for the materiallist to a button and add a subtitle for the tasklist
- [ ] create a state (false) for both tabs, let them toggle the states, if true one of them will be displayed
- [ ] map over the task data and let them be displayed below the button "add new task"

## Complexity

L

**Comment by Mistake91** [comment]
hey marc, your user story looks really good and well thought out 👍
