### ISSUE TITLE
User Story 12: Project Status

### ISSUE THREAD

**Issue by marcterre** [marcterre/capstone-project#23]
## Value Proposition

As a User  
I want to distinguish between my active and inactive projects 
so that i have a easier overview on my landingpage 

## Description

![User Stroy 12](https://user-images.githubusercontent.com/118189611/216353411-0fcd9564-a7eb-432e-ac2c-bf5bb3b931a7.png)

## Acceptance Criteria

- [ ] there is a button on the project details page to set the status for the project
- [ ] the default status of the project is "active"
- [ ] if we click the status button we can toggle between "active" and "inactive"
- [ ] there are now two sections on the landingpage: one for "active projects" and one for "inactive projects"
- [ ] if we set the project status to "active" the button is green and the project will be listed in the "active"-section
- [ ] if we set the project status to "inactive" the button is red and the project will be listed in the "inactive"-section (the opacity of the project name and box decrease)

## Tasks

- [ ] add the status isActive=true to the project array
- [ ] create a button in the project details page which toggles the status
- [ ] create two subtitles on the landingpage: one for "active projects" and one for "inactive projects"
- [ ] filter over the project list on the landingpage
- [ ] if isActive=true the projects should be listed below the subtitle "active projects"
- [ ] if isActive=false the projects should be listed below the subtitle "inactive projects"
- [ ] set a lower opacity for the inactive projects

## Complexity

M

**Comment by Olga-Mishareva** [comment]
LGTM! :)
