### ISSUE TITLE
User Story 13: Styling and categories

### ISSUE THREAD

**Issue by marcterre** [marcterre/capstone-project#25]
## Value Proposition

As a User
i want to have categories for my projects and a presentable overlay
so that i have more info about my project and can easily opearte my app

## Description
The project-view details page will look the same

<img width="766" alt="Screenshot 2023-02-08 at 12 01 58" src="https://user-images.githubusercontent.com/118189611/217512542-2ce0683e-c7de-4fe8-8ddb-458c105bc80b.png">
<img width="423" alt="Screenshot 2023-02-08 at 12 05 25" src="https://user-images.githubusercontent.com/118189611/217512550-ad989702-7ec7-4d68-9df9-28fa9980121c.png">

## Acceptance Criteria

- [ ] the background for every page has the same color
- [ ] the navigation has a consistent color
- [ ] all buttons have the same color, also the links in the navigation
- [ ] if you are on a page which is listed in the navigation the icon background color change to the same color as the page background
- [ ] the listed projects on the landingpage have a consistent color and the category is displayed below the project name
- [ ] there is a new select input on the page "create new project" where you have to select a project category (required)
- [ ] the icons are displayed on the right side of the project name and change the color: if active (green) if inactive (red), same for the status button on the details page
- [ ] on the details page you can toogle between project-views and material list
- [ ] depending on which tab you are the inactiv tab has a lower opacity and the active tab has a border-bottom

## Tasks

- [ ] create a input type=select for the categories (woodwork, metalwork, knitting, stitching, electricity, other)
- [ ] let the category icon and name be displayed on the landingpage and below the image on the details page
- [ ] set the color variables for each color in the global styles
- [ ] assign the background color in the global styles
- [ ] style the navigation with round borders and consitent color
- [ ] style the landingpage and details page as shown in the description: every button should have the same color

## Complexity

XL
