### ISSUE TITLE
User Story 14: Styling and view sides

### ISSUE THREAD

**Issue by marcterre** [marcterre/capstone-project#27]
## Value Proposition

As a User
i want to select view sides for my project views and a presentable overlay
so that i have more info about my project views and can easily opearte my app

## Description

<img width="927" alt="Screenshot 2023-02-08 at 12 16 23" src="https://user-images.githubusercontent.com/118189611/217515756-41ed886a-582f-4c04-9ff5-a5c83909d05f.png">
<img width="448" alt="Screenshot 2023-02-08 at 12 18 20" src="https://user-images.githubusercontent.com/118189611/217515770-09de43a9-97ab-4e96-987a-bf42b9e745c8.png">

## Acceptance Criteria

- [ ]  the modals have the same background color
- [ ] the buttons have a consistent color
- [ ] there is a new select input on the page "add new project view" where you can select a view side
- [ ] the selected view side are displayed with a icon on the project details page and with a small text below the image
- [ ] the background of the materiallist is the same as the page background

## Tasks

- [ ] create a select tag inside the form with options for: front, back, top, bottom, left, right, cut, detail and other
- [ ] import the icons and let them be displayed on the project details page in front of the project view name
- [ ] implement the name of the view side below the image on the project view page
- [ ] style the modals, the view links on the project details page and the materiallist as shown in the wireframes

## Complexity

L
