### ISSUE TITLE
User Story 3: Add new project

### ISSUE THREAD

**Issue by marcterre** [marcterre/capstone-project#3]
## Value Proposition

As a user
I want to add a new project 
so that i can have more different projects listed 

## Description

![User Stroy 3(6)](https://user-images.githubusercontent.com/118189611/214014696-0371e322-fd2d-4f20-917f-c132b134b343.png)

## Acceptance Criteria

- [ ] there is a navigation on the bottom of every page with a home icon and a "+" icon
- [ ] the home icon leads to the landingpage
- [ ] the "+" button leads to the form to create a new project
- [ ] there is a title "create new project" on the top of the screen
- [ ] there is a input to add a title
- [ ] there is a textarea to add a description
- [ ] there is a input to add a new sketch (for now it works with a url)
- [ ] button for "save" is fixed to the bottom of the screen
- [ ] for now submitting the data will display a text "submitted"

## Tasks

- [ ] create a new folder "create-new-project" in "pages" with a index.js inside
- [ ] create a navigation component and fix it on the bottom of the screen
- [ ] inside the navigation component create to links with a home icon and a "+" icon
- [ ] link the home icon to the landingpage and the"+" icon to the "create new project"
- [ ] import the navigation component to the app.js
- [ ] in the create-new-project/index.js:
    - [ ] create a title for the page and fix it on top of the screen
    - [ ] create a form with a text input and a label for the project title
    - [ ] create a textarea and a label for the description
    - [ ] create a input and a label to add a sketch (later replaced with a file input)
    - [ ] create buttons for  "submit" and fix it to the bottom of the screen
- [ ] create a function to handle the submit and show a text if submitted
## Complexity

L

**Comment by AGeck113** [comment]
Very nice structured!  The Complexity looks also really well choosen.
