### ISSUE TITLE
User Story 5:  Add new views

### ISSUE THREAD

**Issue by marcterre** [marcterre/capstone-project#5]
## Value Proposition

As a user
I want to have more than a simple project overview
thats why i want to be able to add more views.

## Description

![User Stroy 5(7)](https://user-images.githubusercontent.com/118189611/214107523-507943a3-9aa3-4814-8acf-b5eef73ae330.png)

## Acceptance Criteria

- [ ] a new subtitle for "views" on the project details page is shown
- [ ] a link "add new  views" leads to a new page "add a new view"
- [ ] there you have a input for "name",a textarea for "description" and a input for "sketch" (for now this works with a url)
- [ ] there are two buttons, one for "cancel" and one for "save"
- [ ] "cancel"-button leads back to the project details
- [ ] "save"-button for now shows a text "submitted"

## Tasks

- [x] create a subtitle on the project details page for views
- [x] create a new page in the pages-folder "add-new-view" with a index.js
- [x] create a link on the project details page which leads to "add-new-view"
- [x] create a title for add-new-view
- [x] create a input for name which is required
- [x] create a textarea for description 
- [x] create a input for sketch (for now works with a url)
- [x] create a "cancel"-button and add a function: onClick leads back to project details
- [x] create a "submit"-button and add a function: for now onClick shows a text "submitted"

## Complexity

L

**Comment by JohannesMisch** [comment]
Hey Marc, I like how detailed you described your tasks. Your user story is fine by me.
